name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

jobs:
  fv-php:
    runs-on: ubuntu-latest
    name: build base image for php
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: ./fv/php
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/fv:php
